#!/bin/sh
### BEGIN INIT INFO
# Provides: neo_server_daemon
# Required-Start: $network $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time for neo_server
# Description: Enable service provided by daemon.
### END INIT INFO
HOMEPATH=/home/pi/neo_server
PID=$(pidof node automation.js)
case "$1" in
    start)
        if [ ! -z "$PID" ]; then
            echo "neo_server is already running"
        else
            cd "$HOMEPATH"
            nice -10 sudo node automation.js > /var/log/neo_server_daemon 2>&1 &
            echo "neo_server starting"
            sleep 2
            "$0" status
        fi
    ;;
    stop)
        if [ -z "$PID" ]; then
            echo "neo_server is not running"
        else
            kill "$PID"
            echo "neo_server closed"
        fi
    ;;
    restart)
        if [ -z "$PID" ]; then
            "$0" start
        else
            "$0" stop
            "$0" start
        fi
    ;;
    status)
        if [ ! -z "$PID" ]; then
            echo "neo_server is running PID $PID"
        else
            echo "neo_server is not running"
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
    ;;
esac

exit 0